amd.f <- formula(POWER_CONSUMPTION ~
				NETWORK_T_BYTES +
				MEMORY_USED +
				MEMORY_RSS +
				MEMORY_RESIDENT +
				MEMORY_FREE +
				MEMORY_CACHED +
				MEMORY_BUFFERS +
				DISK_WRITES_COMPLETED +
				DISK_WEIGHTED_MILLISECONDS_DOING_IO +
				DISK_SECTORS_WRITTEN +
				DISK_MILLISECONDS_WRITING +
				DISK_MILLISECONDS_SPENT_IN_IO +
				DISK_MILLISECONDS_READING +
				DISK_IO_IN_PROGRESS +
				CPU_USER +
				CPU_SYSMODE +
				CPU_IOWAIT +
				CPU_IDLE)

intel.f  <- formula(POWER_CONSUMPTION ~
				NETWORK_T_PACKETS +
				NETWORK_T_BYTES +
				NETWORK_R_PACKETS +
				NETWORK_R_BYTES +
				DISK_WEIGHTED_MILLISECONDS_DOING_IO +
				DISK_MILLISECONDS_SPENT_IN_IO +
				DISK_MILLISECONDS_WRITING +
				DISK_SECTORS_WRITTEN +
				DISK_WRITES_COMPLETED +
				DISK_MILLISECONDS_READING +
				MEMORY_CACHED +
				MEMORY_BUFFERS +
				MEMORY_FREE +
				MEMORY_USED +
				MEMORY_RSS +
				MEMORY_SHARE +
				MEMORY_RESIDENT +	
				CPU_SOFTIRQ +
				CPU_IOWAIT +
				CPU_IDLE +
				CPU_SYSMODE +
				CPU_USER
)

both.f <- formula(POWER_CONSUMPTION ~
				NETWORK_T_PACKETS +
				NETWORK_T_BYTES +
				NETWORK_R_PACKETS +
				NETWORK_R_BYTES +
				MEMORY_USED +
				MEMORY_SIZE +
				MEMORY_SHARE +
				MEMORY_RSS +
				MEMORY_RESIDENT +
				MEMORY_FREE +
				MEMORY_DATA +
				MEMORY_CACHED +
				MEMORY_BUFFERS +
				DISK_WRITES_COMPLETED +
				DISK_WEIGHTED_MILLISECONDS_DOING_IO +
				DISK_SECTORS_WRITTEN +
				DISK_MILLISECONDS_WRITING +
				DISK_MILLISECONDS_SPENT_IN_IO +
				DISK_MILLISECONDS_READING +
				DISK_IO_IN_PROGRESS +
				CPU_USER +
				CPU_SYSMODE +
				CPU_SOFTIRQ +
				CPU_IOWAIT +
				CPU_IDLE +
				ARCH)